# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://www.sgfoot.com/"
#baseURL = "https://yezihack.github.io/"
#baseURL = "https://sgfoot.gitee.io/"
title = "百里江山的博客"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"


hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-163385108-1"      # UA-XXXXXXXX-X
#copyright = "百里江山 | <a href='www.miitbeian.gov.cn'>京ICP备17053344号-1</a>" # default: author.name ↓        # 默认为下面配置的author.name ↓
copyright = "<a href='https://www.sgfoot.com'>百里江山</a>" # default: author.name ↓        # 默认为下面配置的author.name ↓
uglyURLs = true

# Highlight options. 代码区的样式显示.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"  # 默认使用的语言
[Languages.zh-cn]
  languageCode = "zh-cn"

[permalinks]
	post = "/:year/:month/:day/:filename"
	#post = "/:year/:month/:day/:slug"

[author]                  # essential                     # 必需
  name = "百里"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post.html"
[[menu.main]]
  name = "标签云"
  weight = 30
  identifier = "tags"
  url = "/tags.html"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories.html"
[[menu.main]]
  name = "每日算法"
  weight = 40
  identifier = "algo"
  url = "/tags/每日算法.html"

# 谷歌广告
[params.adsense]
  client = "ca-pub-6145899430951391"
  gtag = "UA-163385108-1"

[params]
  since = "2020"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "百里江山的博客"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Go语言", "MySQL", "Redis", "设计模式"]
  description = "Go语言,Golang开发,算法,设计模式,架构,Linux,Kubernetes,Docker-百里江山的个人博客"

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 25

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key
  tencent_analytics = ""    # Tencent Analytics
  baidu_push = false        # baidu push                  # 百度
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = "google8e92341d63465cfb"  # Google_Verification         # 谷歌


  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  # enable 'fork me on github', see https://blog.github.com/2008-12-19-github-ribbons/
  forkMeOnGithub = "https://github.com/yezihack"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
      enable = true
      repo = "yezihack/yezihack.github.io"    # The repo to store comments
      issueTerm = "og:title" # pathname, og:title,url,title,issue-number,specific-term

  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
      enable = true

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
      enable = true
      jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
      slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
      gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
      gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'
      photoswipe = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.js" integrity="sha256-AC9ChpELidrhGHX23ZU53vmRdz3FhKaN9E28+BbcWBw=" crossorigin="anonymous"></script>'
      photoswipeUI = '<script src="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js" integrity="sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=" crossorigin="anonymous"></script>'
      photoswipeCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.css" integrity="sha256-SBLU4vv6CA6lHsZ1XyTdhyjJxCjPif/TRkjnsyGAGnE=" crossorigin="anonymous">'
      photoswipeSKIN = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.css" integrity="sha256-c0uckgykQ9v5k+IqViZOZKc47Jn7KQil4/MP3ySA3F8=" crossorigin="anonymous">'

  [params.search.google]    # google custom search, see https://cse.google.com
      enable = true
      id = "001496614017255051684:v8lrdwgteq1"
      title = "Search"

  [params.reward]                                         # 文章打赏
      enable = true
      wechat = "http://img.sgfoot.com/b/20200417142450.jpg?imageslim"           # 微信二维码
      #alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  [params.social]                                         # 社交链接
    a-email = "mailto:freeit@126.com"
    #b-stack-overflow = "http://localhost:1313"
    #c-twitter = "http://localhost:1313"
    #d-facebook = "http://localhost:1313"
    #e-linkedin = "http://localhost:1313"
    #f-google = "http://localhost:1313"
    g-github = "https://www.github.com/yezihack"
    #h-weibo = "http://localhost:1313"
    #i-zhihu = "http://localhost:1313"
    #j-douban = "http://localhost:1313"
    #k-pocket = "http://localhost:1313"
    #l-tumblr = "http://localhost:1313"
    #m-instagram = "http://localhost:1313"
    #n-gitlab = "http://localhost:1313"
    #o-goodreads = "http://localhost:1313"
    #p-coding = "http://localhost:1313"
    #q-bilibili = "http://localhost:1313"
    #r-codeforces = "http://localhost:1313"
    #s-mastodon = "http://localhost:1313"
